[flavor]
use = "gruvbox-dark"

[icon]
rules = []

[mgr]
ratio = [1, 2, 5]

[preview]
image_protocol = "chafa"

[[filetype.rules]]
url = "*.rs"
mime = "text/x-rust"
# o si es para carpetas/archivos específicos:
# url = "*/"


